### ISSUE TITLE
Breaking releases

### ISSUE THREAD

**Issue by ZsoltMolnarMBH** [TechTeamer/ios-xc-webrtc#1]
Hello TechTeamer,

Braking already released versions, when publishing a new one is a major technical flaw.

# The problem

Our release pipeline is broken since **v1.0.2** was released, due to CocoaPods installation error.
CI error:
```
[!] CocoaPods could not find compatible versions for pod "XCWebRTC":
  In snapshot (Podfile.lock):
    XCWebRTC (= 1.0.0, ~> 1.0.0)
```

After clearing the local cache of CocoaPods, the following error is given:
```
[!] Error installing XCWebRTC
[!] /usr/bin/curl -f -L -o /var/folders/vb/7y23jlfn5q3bfsd3rg8dptdm0000gn/T/d20221111-58207-2qs82x/file.zip https://github.com/TechTeamer/ios-xc-webrtc/raw/master/XCWebRTC/1.0.0/WebRTC.xcframework.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.3 cocoapods-downloader/1.6.3'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
****
```

# The cause

This is a setup issue, which originates from faulty podspec file.
In this case CocoaPods has successfully located the correct podspec file, but that points to the latest commit of the master in order to resolve the framework file, which is independent from the podspec file (while most likely the opposite was expected).

# Suggested solution

Fix the podspec file, by pointing to a fix location.
The conventional way for this kind of solution is:
- Create a GitHub release for the desired version (such as 1.0.2)
- Upload source with compiled release framework in it
- Update the podspec file on master to resolve the framework from the release attachments

Example: https://github.com/CocoaPods/CocoaPods/blob/master/examples/Vendored%20Framework%20Example/Example%20Pods/VendoredFrameworkExample.podspec

Using this method, git LFS could have been avoided too.

**Comment by kelemenjeno** [comment]
Thank you for reporting!

The issue has been resolved. 

Please use the following commands for installation.

**Cocoapods**
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf ~/.cocoapods/repos

In your project dir:
rm podfile.lock
pod deintegrate; pod install

**SPM**
rm -rf ~/Library/Caches/org.swift.swiftpm/repositories

In Xcode click on: File-->Swift Packages-->Reset Package Caches
